<?php

namespace AppBundle\Repository;

/**
 * MetadataFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
