<?php
/**
 * This file is part of the GeRDI software suite
 *
 * @author  Martin Pletl <pletl@lrz.de>
 * @license https://www.apache.org/licenses/LICENSE-2.0
 */
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ResumptionTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumptionTokenRepository extends EntityRepository
{
}
